export default {
  namespaced: true,
  state: () => ({
    orderheaders: [
      {
        text: 'ABCDE (100g serving)',
        align: 'start',
        sortable: false,
        value: 'name',
      },
      { text: 'Calories', value: 'calories' },
      { text: 'Fat (g)', value: 'fat' },
      { text: 'Carbs (g)', value: 'carbs' },
      { text: 'Protein (g)', value: 'protein' },
      { text: 'Iron (%)', value: 'iron' },
      { text: 'Calories2', value: 'calories2' },
      { text: 'Fat (g)2', value: 'fat2' },
      { text: 'Carbs (g)2', value: 'carbs2' },
      { text: 'Protein (g)2', value: 'protein2' },
      { text: 'Iron (%)2', value: 'iron2' },
      { text: 'Calories3', value: 'calories3' },
      { text: 'Fat (g)3', value: 'fat3' },
      { text: 'Carbs (g)3', value: 'carbs3' },
      { text: 'Protein (g)3', value: 'protein3' },
      { text: 'Iron (%)3', value: 'iron3' },
    ],
    orderdesserts: [
      {
        name: 'Frozen Yogurt',
        calories: 159,
        fat: 6.0,
        carbs: 24,
        protein: 4.0,
        iron: '1%',
        calories2: 159,
        fat2: 6.0,
        carbs2: 24,
        protein2: 4.0,
        iron2: '1%',
        calories3: 159,
        fat3: 6.0,
        carbs3: 24,
        protein3: 4.0,
        iron3: '1%',
      },
      {
        name: 'Ice cream sandwich',
        calories: 237,
        fat: 9.0,
        carbs: 37,
        protein: 4.3,
        iron: '1%',
        calories2: 159,
        fat2: 6.0,
        carbs2: 24,
        protein2: 4.0,
        iron2: '1%',
      },
      {
        name: 'Eclair',
        calories: 262,
        fat: 16.0,
        carbs: 23,
        protein: 6.0,
        iron: '7%',
        calories2: 159,
        fat2: 6.0,
        carbs2: 24,
        protein2: 4.0,
        iron2: '1%',
      },
      {
        name: 'Cupcake',
        calories: 305,
        fat: 3.7,
        carbs: 67,
        protein: 4.3,
        iron: '8%',
        calories2: 159,
        fat2: 6.0,
        carbs2: 24,
        protein2: 4.0,
        iron2: '1%',
      },
      {
        name: 'Gingerbread',
        calories: 356,
        fat: 16.0,
        carbs: 49,
        protein: 3.9,
        iron: '16%',
        calories2: 159,
        fat2: 6.0,
        carbs2: 24,
        protein2: 4.0,
        iron2: '1%',
      },
      {
        name: 'Jelly bean',
        calories: 375,
        fat: 0.0,
        carbs: 94,
        protein: 0.0,
        iron: '0%',
        calories2: 159,
        fat2: 6.0,
        carbs2: 24,
        protein2: 4.0,
        iron2: '1%',
      },
      {
        name: 'Lollipop',
        calories: 392,
        fat: 0.2,
        carbs: 98,
        protein: 0,
        iron: '2%',
        calories2: 159,
        fat2: 6.0,
        carbs2: 24,
        protein2: 4.0,
        iron2: '1%',
      },
      {
        name: 'Honeycomb',
        calories: 408,
        fat: 3.2,
        carbs: 87,
        protein: 6.5,
        iron: '45%',
        calories2: 159,
        fat2: 6.0,
        carbs2: 24,
        protein2: 4.0,
        iron2: '1%',
      },
      {
        name: 'Donut',
        calories: 452,
        fat: 25.0,
        carbs: 51,
        protein: 4.9,
        iron: '22%',
        calories2: 159,
        fat2: 6.0,
        carbs2: 24,
        protein2: 4.0,
        iron2: '1%',
      },
      {
        name: 'KitKat',
        calories: 518,
        fat: 26.0,
        carbs: 65,
        protein: 7,
        iron: '6%',
        calories2: 159,
        fat2: 6.0,
        carbs2: 24,
        protein2: 4.0,
        iron2: '1%',
      },
    ],
  }),
  mutations: {
    updateState(state, payload) {
      Object.keys(payload).forEach(key => {
        state[key] = payload[key]
      })
    },
  },
  actions: {
    updateDessert({ state, commit }, payload) {
      console.log('updateDessert: ', payload)
      // for (var i = 0;i < orderdesserts.length; i++) {
        // if(orderdesserts[i].name === payload.name) {
          // console.log('orderdesserts.name: ', orderdesserts[i].name)
          // orderdesserts[i].name === payload.rename
          // console.log('orderdesserts.name: ', orderdesserts[i].name)
        // }
      // }
    }
  }
}